language: python
python:
  - 3.6
  - 3.5

sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker/docker-compose.yml up -d

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: $USER_NAME
  password:
    secure: $SECURE
  on:
    tags: true
    repo: oceanprotocol/oceandb-bigchaindb-driver
    python: 3.6
