version: '2.1'

services:
  # Build: docker-compose build -d bigchaindb
  # Run: docker-compose run -d bdb
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    command: mongod
  bigchaindb:
    depends_on:
      - mongodb
      - tendermint
    image: bigchaindb/bigchaindb:2.0.0-beta1
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 46657
    ports:
      - "9984:9984"
      - "9985:9985"
      - "46658"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://bigchaindb:9984 && curl http://tendermint:46657/abci_query"]
      interval: 3s
      timeout: 5s
      retries: 3
  tendermint:
    image: tendermint/tendermint:0.19.9
    # volumes:
    #   - ./tmdata:/tendermint
    entrypoint: ''
    ports:
      - "46656:46656"
      - "46657:46657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:46658"
  bdb:
    image: busybox
    depends_on:
      bigchaindb:
        condition: service_healthy
  # curl client to check the health of development env
  curl-client:
    image: appropriate/curl
    command: /bin/sh -c "curl -s http://bigchaindb:9984/ > /dev/null && curl -s http://tendermint:46657/ > /dev/null"
  vdocs:
    image: nginx
    ports:
      - '33333:80'
    volumes:
      - ./docs/server/build/html:/usr/share/nginx/html
